### ISSUE TITLE
[Feature Request] Wider range of font sizes

### ISSUE THREAD

**Issue by altsalt** [dan-weiss/apa7-latex-cls-source#18]
The [apa7 font guidelines](https://apastyle.apa.org/style-grammar-guidelines/paper-format/font) mention that figures may use, "a type size between 8 and 14 points." While also pointing to the lack of a definitive recommendation for font families or sizes, beyond being accessible.

The font I'd like to use would probably look a bit better at 14pt, but this is currently unavailable, thus this feature request.

**Comment by dan-weiss** [comment]
The font that is referenced in your link is for text _within_ figure images (likely not generated by `LaTex`) rather than the figure caption itself (generated by `LaTex`). Currently the figure caption font size matches the document font size, which currently has options that fall within the recommended size ranges (10pt-12pt).
